export const ServicesTitle: any = {
  Servicio_de_ensamblaje: [
    "Montaje de muebles (armarios, estanterías, camas, etc.)",
    "Instalación de cocina (muebles de cocina, electrodomésticos, etc.)",
    "Montaje de armarios y sistemas de almacenamiento",
    "Colocación de cuadros, espejos y decoraciones murales",
    "Instalación de lámparas y accesorios de iluminación",
    "Instalación de cortinas, persianas y sistemas de protección solar",
    "Reparaciones domésticas (por ejemplo, puertas dañadas, armarios)",
    "Montaje de soportes para televisores y electrónica de entretenimiento",
    "Tareas generales de mantenimiento (perforación, anclaje, reparaciones menores)",
    "Asesoramiento y asistencia con proyectos de renovación",
  ],
  Técnica_de_aire_acondicionado: [
    "Instalación de sistemas de aire acondicionado (split, multisplit, central)",
    "Mantenimiento y servicio de sistemas de aire acondicionado",
    "Reparación de sistemas de aire acondicionado",
    "Aire acondicionado para espacios residenciales y de oficina",
    "Aire acondicionado para espacios comerciales o industriales",
    "Aire acondicionado para salas de servidores",
    "Instalación de sistemas de ventilación",
    "Mantenimiento y servicio de sistemas de ventilación",
    "Sistemas de purificación de aire y reemplazo de filtros",
    "Consultoría en eficiencia energética y optimización de sistemas climáticos",
    "Asesoramiento para selección y planificación de soluciones climáticas",
  ],
  Albañiles_constructores: [
    "Construcción de estructuras de mampostería (casas, edificios, muros)",
    "Restauración y reparación de mampostería",
    "Instalación de adoquines y aceras",
    "Construcción de cimientos y muros de sótano",
    "Trabajo en concreto (encofrado, vertido de concreto)",
    "Trabajo de nivelación (nivelación de suelos, nivelación)",
    "Instalación de tabiques (paredes, techos, paredes divisorias)",
    "Trabajo de enlucido (enlucido interior y exterior)",
    "Trabajo en fachadas y diseño de fachadas",
    "Trabajo de impermeabilización (por ejemplo, sellado contra la humedad)",
    "Asesoramiento para proyectos de construcción y selección de materiales",
  ],
  Limpieza_de_edificios: [
    "Limpieza de oficinas y comercios",
    "Limpieza de escaleras",
    "Limpieza de ventanas",
    "Limpieza de alfombras y tapicerías",
    "Limpieza de construcción",
    "Limpieza profunda y restauración de suelos",
    "Limpieza de fachadas",
    "Limpieza industrial",
    "Limpieza de vidrio y espejos",
    "Medidas de higiene y desinfección",
    "Control de plagas",
    "Limpieza especial (por ejemplo, después de eventos)",
  ],
  Planificadora_de_construcción: [
    "Planificación y diseño de construcciones",
    "Asesoría en construcción y gestión de proyectos",
    "Permisos de construcción y aprobaciones regulatorias",
    "Consultoría en eficiencia energética",
    "Diseño arquitectónico y planificación de espacios",
    "Planificación de costos y presupuesto de construcción",
    "Supervisión y gestión de construcción",
    "Monitoreo de construcción y control de calidad",
    "Consultoría en sostenibilidad y medio ambiente",
  ],
  Carpinteras: [
    "Fabricación de muebles a medida (armarios, estanterías, mesas)",
    "Instalación de muebles de cocina y armarios",
    "Fabricación e instalación de escaleras y barandillas",
    "Creación de armarios a medida y vestidores",
    "Restauración de muebles antiguos",
    "Reparación y mantenimiento de muebles de madera",
    "Fabricación e instalación de ventanas y puertas",
    "Construcción de estructuras de madera personalizadas",
    "Asesoramiento en selección de especies de madera y tratamiento de superficies",
  ],
  Constructores_de_chimenea: [
    "Planificación y asesoría para sistemas de chimeneas",
    "Instalación de estufas y chimeneas de leña",
    "Renovación y reparación de chimeneas",
    "Trabajo en tapas y cubiertas de chimenea",
    "Revestimientos y materiales de revestimiento para chimeneas",
    "Tapas de chimenea y tubos de humos",
    "Renovación y limpieza de chimeneas",
    "Sistemas de supresión de fuego en chimeneas",
    "Mantenimiento e inspección de sistemas de chimeneas",
    "Asesoramiento para la selección de modelos y opciones de chimeneas",
  ],
  Empresas_de_construcción: [
    "Construcción de nuevos edificios residenciales",
    "Construcción comercial e industrial",
    "Renovación y remodelación de edificios existentes",
    "Construcción llave en mano",
    "Servicios de planificación y arquitectónicos",
    "Gestión de proyectos y supervisión de construcción",
    "Construcción de rascacielos (edificios de apartamentos, oficinas)",
    "Ingeniería civil (carreteras, sistemas de alcantarillado, cimientos)",
    "Construcción de fachadas y envolventes de edificios",
    "Acabados interiores y tabiques",
    "Construcción de instalaciones al aire libre y paisajismo",
    "Soluciones de ahorro energético y sostenibilidad",
  ],
  perforadores_de_hormigón: [
    "Perforación de concreto para instalaciones (por ejemplo, tuberías, cables)",
    "Perforación de núcleos para penetraciones y aperturas",
    "Corte de concreto para paredes divisorias, techos y suelos",
    "Corte de juntas para expansiones y dilataciones",
    "Fresado de concreto para alisado y preparación de superficies",
    "Serrado para demolición y retirada de concreto",
    "Retiro y desmantelamiento de concreto",
    "Reparación y rehabilitación de grietas en concreto",
    "Servicios especializados (por ejemplo, compactación de concreto, medición de temperatura)",
  ],
  Técnico_climático: [
    "Instalación de un nuevo sistema de calefacción",
    "Reparación o mantenimiento de un sistema de calefacción existente",
    "Instalación de una unidad de aire acondicionado o sistema HVAC",
    "Reparación o mantenimiento de una unidad de aire acondicionado o sistema HVAC",
    "Instalación o mantenimiento de sistemas de ventilación",
    "Instalación o reparación de bombas de calor",
    "Instalación o solución de problemas con termostatos",
    "Reemplazo de filtros de aire o mejora de la calidad del aire interior",
    "Consultoría en eficiencia energética y optimización",
  ],
  Talleres_de_automóviles: [
    "Inspección y mantenimiento",
    "Reparación de motor y tren de transmisión",
    "Servicio de frenos y suspensión",
    "Diagnóstico y resolución de problemas",
    "Cambio de aceite y reemplazo de filtros",
    "Reemplazo y servicio de neumáticos",
    "Servicio y mantenimiento de aire acondicionado",
    "Carrocería y pintura",
    "Reparación y reemplazo de parabrisas",
    "Reparaciones eléctricas y electrónicas",
    "Inspección de vehículos (MOT) y pruebas de emisiones",
    "Asesoramiento para compra de vehículos y selección",
  ],
  Instaladores_de_paneles_de_yeso: [
    "Instalación de paredes y techos de paneles de yeso",
    "Instalación de tabiques y divisores de habitación",
    "Instalación de aislamiento (térmico, acústico o protección contra incendios)",
    "Revestimiento de tuberías e instalaciones",
    "Instalación de sistemas de paneles de yeso (por ejemplo, revestimiento)",
    "Construcción de estructuras de paneles de yeso y cartón yeso",
    "Trabajo de paneles de yeso para acabados interiores (por ejemplo, armarios empotrados)",
    "Medidas de protección contra incendios y revestimiento a prueba de fuego",
    "Reparación y renovación de estructuras de paneles de yeso",
    "Asesoramiento en selección de materiales y técnicas de paneles de yeso",
  ],
  Demolición_y_eliminación: [
    "Demolición completa de edificios y estructuras",
    "Demolición parcial/desmantelamiento de edificios",
    "Remoción de asbesto",
    "Eliminación y reciclaje de materiales de construcción",
    "Eliminación de residuos peligrosos",
    "Contenedores y eliminación de residuos",
    "Limpieza de sitios de construcción",
  ],
  Electricista: [
    "Instalaciones eléctricas para nuevas construcciones",
    "Inspección y certificación eléctrica",
    "Instalaciones eléctricas para renovaciones y remodelaciones",
    "Reparaciones y mantenimiento eléctrico",
    "Instalación y actualización de cuadros de fusibles",
    "Instalación de iluminación (interior y exterior)",
    "Instalación de enchufes e interruptores",
    "Instalación de redes y cables de datos",
    "Sistemas de vigilancia por video",
    "Instalación de sistemas de alarma",
    "Integración de casas inteligentes",
    "Resolución de problemas y diagnóstico de averías eléctricas",
    "Asesoramiento y planificación de proyectos eléctricos",
  ],
  Empresas_de_movimiento_de_tierras: [
    "Excavación y trabajos de movimiento de tierras",
    "Nivelación de sitios de construcción",
    "Relleno y compactación de terrenos",
    "Corte y excavación de zanjas para cimientos y tuberías",
    "Excavación de pozos",
    "Eliminación y gestión de escombros",
    "Asesoramiento en selección de equipos y técnicas de excavación",
    "Construcción de caminos y accesos",
    "Trabajos de paisajismo",
    "Remodelación de terrenos y restauración de sitios",
  ],
  Constructores_de_valores: [
    "Construcción de cercas (madera, metal, plástico, etc.)",
    "Instalación de cercas de jardín y propiedad",
    "Instalación de pantallas de privacidad y cercas",
    "Reparación y mantenimiento de la cerca",
    "Instalación de puertas y puertas de entrada",
    "Construcción de gabiones y barreras de ruido",
    "Consulta sobre la selección de materiales y diseños de la cerca",
    "Soluciones de valla personalizada",
    "VERDERACIÓN DE VIAJE Y plantación de plantas trepadoras",
  ],
  Instalador_de_pisos: [
    "Instalación de materiales de piso (por ejemplo, madera dura, laminado, azulejos)",
    "Trabajos de regla (por ejemplo, preparación del sustrato, instalación de regla)",
    "Recubrimientos de piso industriales",
    "Renovación y reparaciones de los pisos",
    "Cubiertas de terraza y balcón",
    "Instalación e integración de calefacción por suelo radiante",
    "Revestimiento de escaleras y renovación",
    "Soluciones de pisos sin barreras",
    "Insonorización e impacto aislamiento de sonido",
    "Consulta para seleccionar los materiales de piso apropiados",
  ],
  Vidriera: [
    "Instalación de ventanas y puertas",
    "Reparación de vidrio y restauración de daños por vidrio",
    "Corte de vidrio y accesorio personalizado",
    "Instalación y fabricación de espejo",
    "Particiones de vidrio y divisores de la habitación",
    "Duchas de vidrio y gabinetes de ducha",
    "Mesas de vidrio y paneles de vidrio",
    "Soluciones de protección contra el vidrio de seguridad y robo",
    "Ventanas de tiendas y cajas de exhibición",
    "GRAZO DEL JARDÍA DE INVIERNO",
    "Consulta sobre tipos y soluciones de vidrio",
  ],
  Instaladoras_de_calefacción: [
    "Instalación de sistemas de calefacción (gas, petróleo o calefacción del distrito)",
    "Instalación de calefacción por suelo radiante",
    "Instalación de radiadores y reemplazo de radiador",
    "Mantenimiento y reparación de sistemas de calefacción",
    "Consultoría de optimización y eficiencia energética",
    "Instalación de termostatos y sistemas de control",
    "Tecnología de condensación e integración de sistemas solares",
    "Ventilación e instalación de tuberías de calefacción",
    "Reparaciones de emergencia en caso de falla de calefacción",
    "Consulta para la selección de sistemas de calefacción",
  ],
  Diseñadores_de_interiores: [
    "Concepto espacial y planificación del espacio",
    "Consulta de color y material",
    "Planificación de muebles y muebles",
    "Diseño de iluminación",
    "Construcción y renovación de interiores",
    "Diseño de pared y papel tapiz",
    "Planificación de pisos y pisos",
    "Decoración de ventana y ventana",
    "Soluciones acústicas e insonorizadas",
    "Diseño sin barreras",
    "Visualización y presentación 3D",
    "Consulta para la selección de muebles y accesorios",
  ],
  Decoradores_de_interiores: [
    "Piso (alfombra, laminado, madera dura, azulejos, etc.)",
    "Decoración de pared (fondos de pantalla, pintura, revestimientos de pared)",
    "Tratamientos de ventana (cortinas, cortinas, persianas, tonos)",
    "Protección solar (toldos, persianas plisadas, persianas)",
    "Servicios de tapicería (replicería de muebles, reparaciones de tapicería)",
    "Planificación y diseño interior",
    "Soluciones acústicas (insonorización, acústica de habitación)",
    "División de salas y planificación del espacio",
    "Muebles y muebles hechos a medida",
    "Consulta sobre selección y diseños de materiales",
  ],
  Instaladores_de_cocinas: [
    "Instalación completa de la cocina (incluidos gabinetes, encimeras, electrodomésticos, etc.)",
    "Instalación o reemplazo del gabinete de cocina",
    "Instalación o reemplazo de la encimera",
    "Instalación de electrodomésticos de cocina",
    "Instalación de protección contra salpicaduras",
    "Instalación o reemplazo de pisos",
    "Instalación de la isla de cocina",
    "Trabajo de carpintería de cocina personalizado",
  ],
  Constructores_de_paisajes: [
    "Planificación y diseño del jardín",
    "Instalación y mantenimiento del césped",
    "Plantación y cuidado de árboles",
    "Construcción del estanque y el jardín de agua",
    "Construcción de terraza y camino",
    "Muro y piedra",
    "Iluminación de jardín y accesorios al aire libre",
    "Pantallas de privacidad e instalaciones de cerca",
    "Sistemas de riego de jardín",
    "Instalación de verdura de techo e techo verde",
    "Mantenimiento y mantenimiento del jardín",
    "Consulta para seleccionar plantas y soluciones de jardín",
  ],
  Empresas_de_mudanzas: [
    "Planificación y organización móviles",
    "Provisión de suministros móviles (cajas, materiales de embalaje)",
    "Servicio de embalaje (embalaje de artículos y muebles)",
    "Desmontaje y ensamblaje de muebles",
    "Transporte de muebles y pertenencias",
    "Carga y descarga de pertenencias",
    "Asamblea de muebles y desmontaje en la nueva ubicación",
    "Limpieza del fin de la tenencia del antiguo apartamento o locales",
    "Almacenamiento de muebles o pertenencias",
    "Asistencia en movimiento para personas mayores o individuales con movilidad limitada",
  ],
  Fabricantes_de_metal: [
    "Fabricación e instalación de estructuras de metales",
    "Metalwork para escaleras, barandas y balcones",
    "Soldadura y reparación de metales",
    "Producción e instalación de cercas y puertas de metal",
    "Fabricación de fachadas de metal y revestimiento",
    "Fabricación de metal (corte, flexión, soldadura)",
    "Fabricación e instalación personalizada de estructuras de acero",
    "Producción de componentes de metal personalizado",
    "Instalación de ventanas y puertas de metal",
    "Consulta para seleccionar materiales y diseños metálicos",
  ],
  Enyesadores: [
    "Pellino interior (liso, texturizado, yeso de lima, etc.)",
    "Pellino exterior (yeso base, yeso de fachada)",
    "Yeso de aislamiento térmico (ética)",
    "Pellido de renovación (por daño por humedad o infestación de moho)",
    "Reparación de daños por yeso (grietas, astillado)",
    "Skimming y suavizado de paredes y techos",
    "Enlucido de particiones de paneles de yeso",
    "Recubrimientos y acabados de yeso",
    "Consulta sobre la selección de tipos y técnicas de yeso",
  ],
  Constructores_de_pavimentos: [
    "Instalación de piedras de pavimento y azulejos de la acera",
    "Construcción de entradas, estacionamientos y superficie del patio",
    "Diseño de terrazas y áreas al aire libre",
    "Construcción de muros de piedra natural y gabiones",
    "Trabajo de asfalto (reparaciones, nueva construcción de carreteras)",
    "Construcción de senderos y senderos para bicicletas",
    "Construcción de sistemas y canales de drenaje",
    "Creación de superficies de concreto (pasarelas, cuadrados)",
    "Consulta para seleccionar materiales y diseños",
    "Renovación y mantenimiento de pavimento y superficies de carretera",
  ],
  Constructores_de_piscinas: [
    "Consulta y planificación para la construcción de piscinas",
    "Construcción de nuevas piscinas",
    "Instalación de piscinas prefabricadas o piscinas diseñadas a medida",
    "Instalación de equipos de piscina (sistema de filtración, bomba, calentador)",
    "Instalación de baldosas de piscina o revestimientos de la piscina",
    "Construcción de cubiertas de piscina y entornos de piscina",
    "Diseño de paisajes de piscina e iluminación de la piscina",
    "Mantenimiento y limpieza de la piscina",
    "Reparación y renovación de las piscinas existentes",
    "Consulta sobre la selección de accesorios y equipos de piscina",
  ],
  Pintores_y_decoradores: [
    "Pintura interior de paredes y techos",
    "Pintura exterior de fachadas",
    "Pintura de puertas, ventanas y superficies de madera",
    "Fondos de pantalla y revestimientos de paredes",
    "Spackling y enlucido",
    "Desmontaje de moho y remediación de humedad",
    "Consulta de color y conceptos de color",
    "Técnicas de pintura decorativa (por ejemplo, acristalamiento, estuco)",
    "Pintura de superficies metálicas (por ejemplo, barandas, escaleras)",
    "Recubrimientos de piso y pintura industrial",
    "Limpieza y protección de la fachada",
    "Consulta para seleccionar colores y materiales",
  ],
  Instaladores_de_fontanería: [
    "Instalación de accesorios de plomería (lavabo, inodoro, ducha, bañera)",
    "Reparación de tuberías y conexiones de agua",
    "Reemplazo o instalación de grifos y accesorios",
    "Instalación de calentadores de agua y calderas",
    "Instalación y mantenimiento de sistemas de calefacción",
    "Instalación y reparación de aguas residuales y sistemas de aguas residuales",
    "Renovación de baños e instalaciones sanitarias",
    "Instalación de sistemas de tratamiento de agua (por ejemplo, suavizantes de agua)",
    "Adaptaciones de accesibilidad para baños (por ejemplo, duchas sin cita)",
    "Consulta sobre la selección de productos e instalación de plomería",
  ],
  Tejadores: [
    "Instalación y reemplazo del techo",
    "Reparación y mantenimiento del techo",
    "Restauración y renovación del techo",
    "Instalación y reparación de canaletas",
    "Aislamiento y aislamiento del techo",
    "Instalación y reemplazo de Skylight",
    "Revestimiento y reparación de fachadas",
    "Sellado y reparación de la chimenea",
    "Recubrimiento y limpieza del techo",
    "Reparaciones de daños por tormentas",
  ],
  Constructores_de_andamios: [
    "Andamios para proyectos de construcción y renovación",
    "Andamio de fachada",
    "Andamios para proyectos de ingeniería civil y de gran altura",
    "Andamio de eventos",
    "Andamios especializados (por ejemplo, para puentes, torres)",
    "Protección del clima y recintos",
    "Alquiler de andamios",
    "Desmantelamiento y extracción de andamios",
    "Inspección de andamios y controles de seguridad",
    "Mantenimiento y reparaciones de andamios",
    "Consulta para la planificación del andamio",
  ],
  Construcción_de_escaleras: [
    "Planificación y diseño de soluciones personalizadas de escaleras",
    "Construcción de nuevas escaleras (madera, metal, concreto, etc.)",
    "Renovación y renovación de las escaleras existentes",
    "Instalación de barandas de escaleras y pasamanos",
    "Paso de escalera y revestimientos de aterrizaje (madera, piedra, azulejos, etc.)",
    "Construcciones de escaleras hechas a medida",
    "Remodelación y expansión de la escalera",
    "Consulta sobre la selección de materiales y diseños de escaleras",
  ],
  Tapiceros_y_guarnicioneros: [
    "Trabajo de tapicería (replicación de muebles, sillas)",
    "Reparación y restauración de muebles tapizados",
    "Fabricación de muebles de tapicería personalizada",
    "Producción de cojines y respaldos",
    "Creación de cubiertas para tapicería para el asiento del automóvil",
    "Trabajo de tapicería para barcos y yates",
    "Trabajo de saddlery (replicamiento de asientos de automóvil, asientos de motocicleta)",
    "Fabricación de bolsas y accesorios de cuero personalizados",
    "Restauración de muebles antiguos y artículos de cuero",
    "Consulta sobre selección de telas y tipos de cuero",
  ],
  Azulejeros: [
    "Instalación de azulejos para pisos",
    "Instalación de mosaicos para paredes",
    "Instalación de baldosas para cocinas y baños",
    "Terrace y balcón de balcón",
    "Instalación de piedra natural",
    "Mosaico y azulejos decorativos",
    "Corte de baldosas y accesorio",
    "Sellado y sellado de lechada",
    "Renovación y reparación de azulejos",
    "Soluciones sin barreras para pisos y duchas",
    "Consulta para seleccionar mosaicos y diseños",
  ],
  Empresas_de_transporte: [
    "Servicios de mudanza (reubicación residencial o comercial)",
    "Transporte y montaje de muebles",
    "Entregas y transportes locales y regionales",
    "Transporte de larga distancia (nacional o internacional)",
    "Entrega expresa y servicios de mensajería",
    "Transporte de productos voluminosos o pesados",
    "Servicios de almacenamiento y almacenamiento",
    "Servicios de eliminación (eliminación de residuos, eliminación de chatarra)",
    "Transporte especializado (por ejemplo, transporte de materiales peligrosos)",
    "Consulta y planificación de soluciones de transporte",
  ],
  Constructores_de_pozos: [
    "Drinción de pozos de agua potable",
    "Pozos para fines agrícolas",
    "Pozos para sistemas de riego",
    "Pozos para sistemas de calefacción y refrigeración geotérmica",
    "Pozos para fines industriales",
    "Mantenimiento y reparaciones de pozos",
    "Selección e instalación de la bomba",
    "Pruebas y análisis de calidad del agua",
    "Consulta para la selección y planificación de los pozos",
  ],
  Construcción_de_ventanas: [
    "Fabricación e instalación de ventanas",
    "Fabricación e instalación de puertas",
    "Toldo de fabricación e instalación",
    "Instalación y reparación del obturador del rodillo",
    "Construcción del conservatorio y acristalamiento",
    "Vidry and Grazing Works",
    "Instalación de la pantalla de insectos",
    "Soluciones de protección de robo",
    "Soluciones sin barreras para ventanas y puertas",
    "Soluciones de protección solar (por ejemplo, persianas, persianas plisadas)",
    "Reparación y mantenimiento de las ventanas y puertas",
    "Consulta para seleccionar ventanas, puertas y toldos",
  ],
  Preservación_de_la_madera: [
    "Preservación de madera e impregnación de madera",
    "Protección de edificios contra la humedad y el moho",
    "Control de plagas en el sector de madera y construcción",
    "Sellado y revestimiento estructural",
    "Implazamiento del agua del sótano y remediación de humedad",
    "Impregnación y protección de la fachada",
    "Balcón y recubrimiento de terraza",
    "Restauración y reparación de la madera",
    "Renovación y protección de la armadura de techo",
    "Consulta sobre prevención de daños",
  ],
};
